apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-test
          image: stormmind/backend-test:latest 
          ports:
            - containerPort: 8080
          env:
            - name: open_meteo_api_key
              value: "DEIN_KEY_HIER"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: None 