apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-test
          image: stormmind/backend-test:latest # → Wird durch Tekton gesetzt
          ports:
            - containerPort: 3000
          env:
            - name: open_meteo_api_key
              value: "DEIN_KEY_HIER"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: None # → Für Headless-Service bei direkter Verbindung, optional