apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-test
          image: stormmind/frontend-test:latest
          env:
            - name: BACKEND_URL
              value: "http://backend:3000"
          ports:
            - containerPort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 30443
      targetPort: 30443