apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: stormmind-vs
  namespace: prod
spec:
  hosts:
  - "stormmind.ch"
  gateways:
  - stormmind-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-service
        port:
          number: 443