apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
    - name: buildRevision
    - name: appGitUrl
    - name: appSubDir
    - name: configGitUrl
    - name: configSubDir
    - name: registryPublic
    - name: gatewayHost
    - name: imageName
    - name: imageTag
      default: latest
    - name: DOCKERFILE
      description: Path to Dockerfile
    - name: CONTEXT
      description: Path to build context
  workspaces:
    - name: app-source
    - name: config-source
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.appGitUrl)
        - name: revision
          value: $(params.buildRevision)
        - name: subdirectory
          value: $(params.appSubDir)
      workspaces:
        - name: output
          workspace: app-source

    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: app-source
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: IMAGE
          value: $(params.registryPublic)/$(params.imageName):latest
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: CONTEXT
          value: $(params.CONTEXT)