apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-checkout
spec:
  params:
  - name: url
    description: Repository URL to clone from.
    type: string
  - name: revision
    description: Revision to checkout. (branch, tag, sha, ref, etc...)
    type: string
    default: ""
  workspaces:
  - name: output
    description: The git repo will be cloned onto the volume backing this Workspace.
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.output.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      rm -rf * .[a-zA-Z]*
      git init
      git remote add origin $(params.url)
      git fetch --depth 1 origin $(params.revision)
      git checkout FETCH_HEAD
      
      # publish result values
      RESULT_SHA="$(git rev-parse HEAD)"
      EXIT_CODE="$?"
      if [ "${EXIT_CODE}" != 0 ] ; then
          exit "${EXIT_CODE}"
      fi
      printf "%s" "${RESULT_SHA}" > "$(results.commit.path)"
      printf "%s" "$(params.url)" > "$(results.url.path)"
