apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: stormmind-build-deploy-backend-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
    - name: buildRevision
      value: 'main'
    - name: appGitUrl
      value: 'https://github.com/stormmind-ch/backend.git'
    - name: appSubDir
      value: ''
    - name: configGitUrl
      value: 'https://github.com/stormmind-ch/infrastructure.git'
    - name: configSubDir
      value: ''
    - name: registryPublic
      value: 'stormmind'
    - name: gatewayHost
      value: 'stormmind.ch'
    - name: imageName
      value: 'backend-test'
    - name: imageTag
      value: 'latest'
  workspaces:
    - name: app-source
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1.0Gi
    - name: config-source
    - name: docker-credentials
      secret:
        secretName: docker-credentials
      emptyDir: {}