apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: stormmind-build-deploy-backend-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
    - name: buildRevision
      value: 'main'
    - name: appGitUrl
      value: 'https://github.com/stormmind-ch/backend.git'
    - name: appSubDir
      value: 'src'
    - name: configGitUrl
      value: 'https://github.com/stormmind-ch/infrastructure.git'
    - name: configSubDir
      value: ''
    - name: registryPublic
      value: 'docker.io/stormmind'
    - name: gatewayHost
      value: 'stormmind.ch'
    - name: imageName
      value: 'stormmind/backend_test'
  workspaces:
    - name: app-source
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1.0Gi
    - name: config-source
      emptyDir: {}