services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - webnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge