apiVersion: v1
kind: Service
metadata:
  name: nginx_service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer # ⬅️ oder NodePort, je nach Cluster-Setup