apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: tekton-pipelines-run
  annotations:
    # this secret will be selected following domains
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: duke-j
  password: ###github token###

