apiVersion: v1
kind: Secret
metadata:
  name: nginx-cert
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded fullchain.pem>
  tls.key: <base64 encoded privkey.pem>
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-options
type: Opaque
data:
  options-ssl-nginx.conf: <base64 encoded options-ssl-nginx.conf>
  ssl-dhparams.pem: <base64 encoded ssl-dhparams.pem>