apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hostname
  name: hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hostname
        image: ruanbekker/hostname:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {
            "requests": {
                "cpu": "100m",
                "memory": "128Mi"
            },
            "limits": {
                "cpu": "200m",
                "memory": "256Mi"
            }
        }
          
---

apiVersion: v1
kind: Service
metadata:
  name: hostname-service
spec:
  type: ClusterIP
  selector:
    app: hostname
  ports:
    - protocol: TCP
      port: 443
      targetPort: 30443
      name: https

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostname-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    #cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: stormmind.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hostname-service
            port:
              number: 80
  tls:
  - hosts:
    - stormmind.ch
    secretName: hostname-tls-cert